version: '3.8'

services:
  patinhas_app:
    build:
      context: ./app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - patinhas-network
    depends_on:
      - patinhas_api
      - patinhas_db

  patinhas_api:
      build:
        context: ./api
      volumes:
        - ./api/src:/app/src
        - /app/node_modules
      ports:
        - "4000:4000"
      networks:
        - patinhas-network
      depends_on:
      - patinhas_db

  patinhas_db:
    image: mysql:8.0
    container_name: patinhas_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: patinhas_carentes_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - patinhas-network

volumes:
  mysql-data:

networks:
  patinhas-network:
    driver: bridge
